baseURL = '/'
languageCode = 'en-us'
title = '盧瞳小站'
theme  =  "reimu"

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true